fix NoSuchMethodError in filter
I got errors when using `filter` for objects that is nullable.
I seem to be no substantial problem.
However, I want to suppress unwanted errors.

```
The null object does not have a method 'toList'.

NoSuchMethodError: method not found: 'toList'
Receiver: null
Arguments: [growable: false]

STACKTRACE:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#1      Filter.call (package:angular/formatter/filter.dart:193:26)
...
```