fix(parser): Correctly distinguish NoSuchMethodError
When evaluating 'a.foo' we could get NoSuchMethodError
due to 'a' not having 'foo' or 'a' has 'foo' and
the getter throws NoSuchMethodError.

Fix #504